name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
      name: firmware
      path: firmware*.bin

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
      repo_token: ${{ secrets.GITHUB_TOKEN }}
      file: firmware.packed.bin
      asset_name: egzumer_$tag.packed.bin
      tag: ${{ github.ref }}
      overwrite: true
      release_name: release ${{ github.ref_name }}
